### ISSUE TITLE
Code C# error in the 'Qwen2-1.5B-Instruct-q4f32_1-MLC' model

### ISSUE THREAD

**Issue by Yoko-0x0** [DevJaGz/npm-chat#3]
input: "dame un ejemplo de como crear un linq en C#"
bot: "Para crear un Linq en C"

It seems to be a problem with the model when responding with #

i tested with 'Llama-3-8B-Instruct-q4f32_1-MLC-1k' model is working.

![image](https://github.com/DevJaGz/npm-chat/assets/18251038/19f2cff2-d3e7-4643-9209-3544fc4b0055)

**Comment by DevJaGz** [comment]
Hello there! I appreciate your interest!

Yep, sometimes the current model is not very smart, but it is much faster than the `Llama-3-8B-Instruct-q4f32_1-MLC-1k`. Based on that, I think the `Qwen2-1.5B-Instruct-q4f32_1-MLC`model is a good choice for now because it strikes a balance between being smart and fast.
